### ISSUE TITLE
Freature request: Include Input devices

### ISSUE THREAD

**Issue by emiliopedrollo** [marcinjahn/gnome-quicksettings-audio-devices-hider-extension#1]
First of all, awesome extension.

Would it be possible to add filters for input devices as well?

**Comment by emiliopedrollo** [comment]
I've tried to use the same logic from outputs but for inputs but it appears to not be that simple. Or maybe i'm not getting something.

**Comment by marcinjahn** [comment]
Hi @emiliopedrollo, thanks, I'm glad you found the extension useful.
Addin inputs support definitely was on my list of things to do. Outputs are just something that I switch much more often, and I prioritized that feature. However, I see that you already took the swing at adding inputs, I'll review the PR later on.
I assume that you managed to get it to work, and your last comment is outdated? :)

**Comment by emiliopedrollo** [comment]
It's was already working on that commit, I just haven't make an extensive test. The issue I was having was related to another extension.

In `Quick Settings Audio Panel` I have the option `Always show microphone volume slider` on and for some reason when I change some option on the `Quick Settings Audio Devices Hider` the slider itself hides. Restarting the other extension or the GE itself restored the slider with only the selected devices so I think it's acceptable.

**Comment by marcinjahn** [comment]
Got it. Myself I use [Quick Settings Tweaker](https://extensions.gnome.org/extension/5446/quick-settings-tweaker/) for the same purpose, and I didn't notice any issues so far.

**Comment by marcinjahn** [comment]
The new version (5) has been submitted to EGO. I'll update this topic when it gets released.

**Comment by marcinjahn** [comment]
v6 is out at https://extensions.gnome.org/extension/5964/quick-settings-audio-devices-hider/
