### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by mtompkins** [marcinjahn/gnome-quicksettings-audio-devices-hider-extension#11]
Would love to see this updated for Gnome 46

**Comment by marcinjahn** [comment]
Currently, I do not have access to Gnome 46 system, and testing this on a VM is not great. If you had upgraded to Gnome 46, it'd be awesome if you could test if the extension works there.
Instrucitons are the same as I outlined in another extension's issue: https://github.com/marcinjahn/gnome-peek-top-bar-on-fullscreen-extension/issues/17#issuecomment-2018723763

The path to `metadata.json` would be `$HOME/.local/share/gnome-shell/extensions/quicksettings-audio-devices-hider@marcinjahn.com/metadata.json` though.

**Comment by mrpendulum** [comment]
> Currently, I do not have access to Gnome 46 system, and testing this on a VM is not great. If you had upgraded to Gnome 46, it'd be awesome if you could test if the extension works there. Instrucitons are the same as I outlined in another extension's issue: [marcinjahn/gnome-peek-top-bar-on-fullscreen-extension#17 (comment)](https://github.com/marcinjahn/gnome-peek-top-bar-on-fullscreen-extension/issues/17#issuecomment-2018723763)
> 
> The path to `metadata.json` would be `$HOME/.local/share/gnome-shell/extensions/quicksettings-audio-devices-hider@marcinjahn.com/metadata.json` though.

Edited metadata.json, updated version to 46, restarted gnome-shell. and full functional, I can't fault anything.

**Comment by marcinjahn** [comment]
Thanks @penn-dulum. I did what every sane person would do, and I trusted a random guy on the Internet. The updated version should soon appear on https://extensions.gnome.org/extension/5964/quick-settings-audio-devices-hider/

Btw, I also updated https://extensions.gnome.org/extension/6000/quick-settings-audio-devices-renamer/, if any of you happen to use this one as well.

**Comment by marcinjahn** [comment]
It's live, closing
