### ISSUE TITLE
Can't hide EasyEffects Sink

### ISSUE THREAD

**Issue by diegopvlk** [marcinjahn/gnome-quicksettings-audio-devices-hider-extension#4]
Hey, thanks for this extension!

The only problem I have is with the EasyEffects sink:
![](https://github.com/marcinjahn/gnome-quicksettings-audio-devices-hider-extension/assets/25941156/8bd4a91b-6ea1-45f0-a9f6-de74f6a0a5f2)

It is possible to hide this output?

**Comment by marcinjahn** [comment]
Hi @diego-pvlk, interesting, I will have a look

**Comment by marcinjahn** [comment]
@diego-pvlk The issue should be gone in version 8. I already submitted it for review to Gnome Extensions, you should get an update soon. Let me know if it works now.

If you find the extension useful, consider starring the repository :wink:
