### ISSUE TITLE
Not an issue(?) running on Gnome 43

### ISSUE THREAD

**Issue by Milliw** [marcinjahn/gnome-quicksettings-audio-devices-hider-extension#5]
Hi!
Just wanted to quickly leave the info that I have manually installed this on my system running Gnome 43 and so far it seems to run fine.

Thanks for that handy extension and kind regards =)

**Comment by marcinjahn** [comment]
Thanks for your kind words! It’a awesome to see that this thing makes someone’s experience better.

I’m curious, why did you install it manually, and not via the “store”?

**Comment by Milliw** [comment]
> Thanks for your kind words! It’a awesome to see that this thing makes someone’s experience better. Consider starring the repository, it’s always nice to see that.

You're welcome! =)
> I’m curious, why did you install it manually, and not via the “store”?
Because it said "incompatible" and therefore I had to manually alter the version number in _metadata.json_ or at least I thought I had to do this, too to manually install it.

**Comment by marcinjahn** [comment]
Oh, now I get it, I totally missed the “Gnome 43” part. Then, I guess, it makes sense to add 43 to the manifest as a supported version. If you want, you can create a PR for that, or I might do it a bit later.

**Comment by Milliw** [comment]
> Oh, now I get it, I totally missed the “Gnome 43” part. Then, I guess, it makes sense to add 43 to the manifest as a supported version. 

Ah yeah. Easy to miss, it's only in the title ^^

> If you want, you can create a PR for that, or I might do it a bit later.
I'm not really familiar in doing such a thing, sorry if it might look like.

**Comment by marcinjahn** [comment]
No problem, I still suggest you to give it a try, it’s not that difficult. What you need to do, is:
1. fork this repository (a button somewhere at the top). This basically creates a copy of the whole project, which you can freely manage
2. Modify the manifest.json file in your fork, probably similarly to how you did it locally. You can do it within GitHub by navigating to the file, editing it, and commiting changes (make sure that you are in your fork)
3. After commiting the change, there should be some button/link to create a Pull Request to the upstream repo (this one)

If you don’t want to do that, no worries, I can update it myself as well.

**Comment by marcinjahn** [comment]
Thanks, it's merged, you should be able to install the extension from EGO now (https://extensions.gnome.org/extension/5964/quick-settings-audio-devices-hider/). Even though you already have it installed manually, installation from EGO gives you the benefit of auto-updates.


> Why wasn't 43 in there from start?

I'm running Gnome 44, and did not test it on any earlier version of Gnome, so 44 was the only version I was sure to be working. And now, trusting that your report is accurate, 43 was added as well.
