### ISSUE TITLE
Support renaming devices

### ISSUE THREAD

**Issue by ronjouch** [marcinjahn/gnome-quicksettings-audio-devices-hider-extension#7]
Hi! Love the extension, it's working great for me.

Still, even after having pruned devices I never use, it still takes me a couple seconds to piece together which device is which, given their cryptic / generic / nondescriptive names.

For example, I'd rename my devices as such:

- `Speakers - USB Audio Device` to `Headphones over USB`
- `HDMI - DisplayPort - Builtin Audio` to `Monitor`
- `Speakers - Built-in Audio` to `Laptop`

It would make things muuuuuuuuuuuuuch more pleasant!

Hope you can consider it! At any rate, thanks for the extension 🙂.

**Comment by marcinjahn** [comment]
Hi @ronjouch, thanks, consider starring the repository, it's always nice to see that.

Renaming devices is something that did cross my mind at some point, I also find the default names to be a bit too descriptive sometimes. Thanks for reminding me about that, I will have a look at that feature.

**Comment by emko** [comment]
> Hi! Love the extension, it's working great for me.
> 
> Still, even after having pruned devices I never use, it still takes me a couple seconds to piece together which device is which, given their cryptic / generic / nondescriptive names.
> 
> For example, I'd rename my devices as such:
> 
>     * `Speakers - USB Audio Device` to `Headphones over USB`
> 
>     * `HDMI - DisplayPort - Builtin Audio` to `Monitor`
> 
>     * `Speakers - Built-in Audio` to `Laptop`
> 
> 
> It would make things muuuuuuuuuuuuuch more pleasant!
> 
> Hope you can consider it! At any rate, thanks for the extension slightly_smiling_face.

yes this would be great, i used to be able to edit the device name  and disable devices in wireplumer on gnome 43 but it does not work anymore so it would be nice if this extension could make renaming them easier :+1:

**Comment by marcinjahn** [comment]
@ronjouch, @emko. I've created a new extension specifically for the purpose of renaming devices in the panel - https://github.com/marcinjahn/gnome-quicksettings-audio-devices-renamer-extension

I didn't want to extend "hider" with that functionality, I think extensions should be small and do one thing, unless it's too complex to separate features into different projects.

**Comment by ronjouch** [comment]
@marcinjahn sure! Reviewed and installed, works for me on Shell 44.1 🙂. Thaaaaaaaaaaaaanks!

A lil' suggestion that might halp a couple users: mention the other "companion" extension in the README / exts.gnome.org page of each extension.
