### ISSUE TITLE
Extension does not hide audio outputs on secondary monitors

### ISSUE THREAD

**Issue by Uptaker** [marcinjahn/gnome-quicksettings-audio-devices-hider-extension#9]
Hi!

First of all - thank you so much for the extension! Makes switching a breeze by removing all the clutter.

## Issue
I've noticed that the extension doesn't seem to hide audio outputs on secondary monitors -  at least on my dual monitor setup.

[Recording](https://github.com/marcinjahn/gnome-quicksettings-audio-devices-hider-extension/assets/16374628/f4554c33-2e26-4a6a-b974-a91329808ced)

I'm using the latest Fedora 39 for reference.

I don't have any input devices to confirm if it's the same with those.

**Comment by marcinjahn** [comment]
Hi @Uptaker, I guess you achieved panel visibility on multiple monitors via some other extension, right? Multiple extensions modifying the same areas of the Shell will usually cause issues, and I don't think I could do anything about it. Well, most likely it'd be possible to add support for the specific extension that you're using, but it's not something I'd like to maintain later on.

**Comment by Uptaker** [comment]
It seems you're right.

I've been using [App Icons Taskbar](https://extensions.gnome.org/extension/4944/app-icons-taskbar/) in my workflow for so long that I forgot default GNOME has no taskbar on other monitors.

**Comment by Ana06** [comment]
This is also happens to me, likely because of [Dash To Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/). I really like this extension, but it is very confusing that I get more devices in different monitors. :sob:

**Comment by Ana06** [comment]
The same applies to Quick Settings Audio Devices Renamer

**Comment by marcinjahn** [comment]
Yeah, as you can imagine, supporting all the different use cases and custom modifications is a bit of a pain :smiling_face_with_tear:
